version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g @angular/cli
      - npm install
  pre_build:
    commands:
      - ng build --prod
  build:
    commands:
      - aws s3 sync ./dist/ s3://arn:aws:s3:::angular-app-cpp1 --delete

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
